source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.9'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.7'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 2.22'
  gem 'jsonapi-rspec'
  gem 'pry-rescue', '~> 1.5'
  gem 'pry-stack_explorer', '~> 0.6.1'
  gem 'rspec', '~> 3.12'
  gem 'rspec-activemodel-mocks', '~> 1.1'
  gem 'rspec-openapi', '~> 0.7.2'
  gem 'rspec-rails'
  gem 'simplecov', '~> 0.21.2'
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'debase', '~> 0.2.4'
  gem 'pry-rails', '~> 0.3.9'
  gem 'rubocop', '~> 1.40'
  gem 'ruby-debug-ide', '~> 0.7.3'
  gem 'solargraph', '~> 0.47.2'
  gem 'spring'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'devise', '~> 4.8'
gem 'devise-jwt', '~> 0.10.0'
gem 'jsonapi-rails', '~> 0.4.1'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

gem 'aws-sdk-s3', '~> 1.117'
gem 'sidekiq', '~> 6.5'
